// image.assets/book_repository.dart

import 'package:flutter/material.dart';

import 'book_model.dart';

class BookRepository {
  Future<List<Book>> getBooksByCategory(String category) async {
    // In a real app, this would fetch from API or database
    // Here's mock data with real books available in Egypt
    final List<Book> allBooks = [
      // Fiction
      Book(
        id: '1',
        title: 'The Yacoubian Building',
        author: 'Alaa Al Aswany',
        category: 'Fiction',
        description: 'A novel about life in downtown Cairo, centered around the residents of the Yacoubian Building.',
        ownerId: 'owner1',
        ownerName: 'Mohamed Ahmed',
        ownerContact: '01012345678',
        imageUrl: 'assets/images/Fiction1.jpg', // Local image path
        price: "Exchange",
        condition: 'Like New',
        publishedDate: DateTime(2002),
        isAvailable: true,
      ),
      Book(
        id: '2',
        title: 'The Kite Runner',
        author: 'Khaled Hosseini',
        category: 'Fiction',
        description: 'A powerful story of friendship, betrayal, and redemption set in Afghanistan.',
        ownerId: 'owner2',
        ownerName: 'Ahmed Hassan',
        ownerContact: '01023456789',
        imageUrl: 'assets/images/Fiction2.jpg',
        price: "150 EGP",
        condition: 'Good',
        publishedDate: DateTime(2003),
        isAvailable: true,
      ),
      Book(
        id: '3',
        title: '1984',
        author: 'George Orwell',
        category: 'Fiction',
        description: 'A dystopian novel about totalitarianism and surveillance.',
        ownerId: 'owner3',
        ownerName: 'Yara Mahmoud',
        ownerContact: '01034567890',
        imageUrl: 'assets/images/Fiction3.jpg',
        price: "Exchange",
        condition: 'Used',
        publishedDate: DateTime(1949),
        isAvailable: true,
      ),
      Book(
        id: '4',
        title: 'The Alchemist',
        author: 'Paulo Coelho',
        category: 'Fiction',
        description: 'A philosophical novel about a shepherd’s journey to find his destiny.',
        ownerId: 'owner4',
        ownerName: 'Nada Samir',
        ownerContact: '01045678901',
        imageUrl: 'assets/images/Fiction4.jpg',
        price: "90 EGP",
        condition: 'Like New',
        publishedDate: DateTime(1988),
        isAvailable: true,
      ),
      Book(
        id: '5',
        title: 'Pride and Prejudice',
        author: 'Jane Austen',
        category: 'Fiction',
        description: 'A classic romance novel about the Bennet family and Mr. Darcy.',
        ownerId: 'owner5',
        ownerName: 'Mariam Adel',
        ownerContact: '01056789012',
        imageUrl: 'assets/images/Fiction5.jpg',
        price: "Exchange",
        condition: 'Good',
        publishedDate: DateTime(1813),
        isAvailable: true,
      ),
      Book(
        id: '6',
        title: 'The Great Gatsby',
        author: 'F. Scott Fitzgerald',
        category: 'Fiction',
        description: 'A story of wealth, love, and tragedy in 1920s America.',
        ownerId: 'owner6',
        ownerName: 'Omar Khaled',
        ownerContact: '01067890123',
        imageUrl: 'assets/images/Fiction6.jpg',
        price: "110 EGP",
        condition: 'Used',
        publishedDate: DateTime(1925),
        isAvailable: true,
      ),
      Book(
        id: '7',
        title: 'To Kill a Mockingbird',
        author: 'Harper Lee',
        category: 'Fiction',
        description: 'A novel about racial injustice and moral growth in the American South.',
        ownerId: 'owner7',
        ownerName: 'Lina Sherif',
        ownerContact: '01078901234',
        imageUrl: 'assets/images/Fiction7.jpg',
        price: "Exchange",
        condition: 'Good',
        publishedDate: DateTime(1960),
        isAvailable: true,
      ),
      Book(
        id: '8',
        title: 'The Da Vinci Code',
        author: 'Dan Brown',
        category: 'Fiction',
        description: 'A thriller involving art, religion, and secret societies.',
        ownerId: 'owner8',
        ownerName: 'Karim Waleed',
        ownerContact: '01089012345',
        imageUrl: 'assets/images/Fiction8.jpg',
        price: "130 EGP",
        condition: 'Like New',
        publishedDate: DateTime(2003),
        isAvailable: true,
      ),
      Book(
        id: '9',
        title: 'One Hundred Years of Solitude',
        author: 'Gabriel García Márquez',
        category: 'Fiction',
        description: 'A magical realism novel following the Buendía family in Macondo.',
        ownerId: 'owner9',
        ownerName: 'Dalia Nasser',
        ownerContact: '01090123456',
        imageUrl: 'assets/images/Fiction9.jpg',
        price: "Exchange",
        condition: 'Good',
        publishedDate: DateTime(1967),
        isAvailable: true,
      ),
      Book(
        id: '10',
        title: 'The Hobbit',
        author: 'J.R.R. Tolkien',
        category: 'Fiction',
        description: 'A fantasy adventure about Bilbo Baggins and his quest for treasure.',
        ownerId: 'owner10',
        ownerName: 'Ziad Farouk',
        ownerContact: '01001234567',
        imageUrl: 'assets/images/Fiction10.jpg',
        price: "160 EGP",
        condition: 'Like New',
        publishedDate: DateTime(1937),
        isAvailable: true,
      ),
      Book(
        id: '11',
        title: 'The Catcher in the Rye',
        author: 'J.D. Salinger',
        category: 'Fiction',
        description: 'A coming-of-age novel about teenage rebellion and alienation.',
        ownerId: 'owner11',
        ownerName: 'Hana Tarek',
        ownerContact: '01012345098',
        imageUrl: 'assets/images/Fiction11.jpg',
        price: "Exchange",
        condition: 'Used',
        publishedDate: DateTime(1951),
        isAvailable: true,
      ),

      // Non-Fiction
      Book(
        id: '12',
        title: 'Sapiens: A Brief History of Humankind',
        author: 'Yuval Noah Harari',
        category: 'Non-Fiction',
        description: 'Explores the history of Homo sapiens from ancient times to the modern era.',
        ownerId: 'owner12',
        ownerName: 'Ali Mohamed',
        ownerContact: '01011223344',
        imageUrl: 'assets/images/Non-Fiction1.jpg',
        price: "Exchange",
        condition: 'Like New',
        publishedDate: DateTime(2011),
        isAvailable: true,
      ),
      Book(
        id: '13',
        title: 'Atomic Habits',
        author: 'James Clear',
        category: 'Non-Fiction',
        description: 'A guide to building good habits and breaking bad ones through small changes.',
        ownerId: 'owner13',
        ownerName: 'Nour Ibrahim',
        ownerContact: '01022334455',
        imageUrl: 'assets/images/Non-Fiction2.jpg',
        price: "150 EGP",
        condition: 'Good',
        publishedDate: DateTime(2018),
        isAvailable: true,
      ),
      Book(
        id: '14',
        title: 'Becoming',
        author: 'Michelle Obama',
        category: 'Non-Fiction',
        description: 'A memoir by the former First Lady of the United States.',
        ownerId: 'owner14',
        ownerName: 'Fatma Adel',
        ownerContact: '01033445566',
        imageUrl: 'assets/images/Non-Fiction3.jpg',
        price: "Exchange",
        condition: 'Like New',
        publishedDate: DateTime(2018),
        isAvailable: true,
      ),
      Book(
        id: '15',
        title: 'The Power of Now',
        author: 'Eckhart Tolle',
        category: 'Non-Fiction',
        description: 'A spiritual guide to living in the present moment.',
        ownerId: 'owner15',
        ownerName: 'Youssef Samy',
        ownerContact: '01044556677',
        imageUrl: 'assets/images/Non-Fiction4.jpg',
        price: "120 EGP",
        condition: 'Used',
        publishedDate: DateTime(1997),
        isAvailable: true,
      ),
      Book(
        id: '16',
        title: 'Quiet: The Power of Introverts in a World That Can’t Stop Talking',
        author: 'Susan Cain',
        category: 'Non-Fiction',
        description: 'Explores the strengths of introverts in an extrovert-dominated society.',
        ownerId: 'owner16',
        ownerName: 'Mona Hany',
        ownerContact: '01055667788',
        imageUrl: 'assets/images/Non-Fiction5.jpg',
        price: "Exchange",
        condition: 'Good',
        publishedDate: DateTime(2012),
        isAvailable: true,
      ),
      Book(
        id: '17',
        title: 'The 7 Habits of Highly Effective People',
        author: 'Stephen R. Covey',
        category: 'Non-Fiction',
        description: 'A self-improvement book focusing on personal and professional success.',
        ownerId: 'owner17',
        ownerName: 'Kareem Ali',
        ownerContact: '01066778899',
        imageUrl: 'assets/images/Non-Fiction6.jpg',
        price: "140 EGP",
        condition: 'Used',
        publishedDate: DateTime(1989),
        isAvailable: true,
      ),
      Book(
        id: '18',
        title: 'Educated',
        author: 'Tara Westover',
        category: 'Non-Fiction',
        description: 'A memoir about a woman who leaves her survivalist family to pursue education.',
        ownerId: 'owner18',
        ownerName: 'Dina Magdy',
        ownerContact: '01077889900',
        imageUrl: 'assets/images/Non-Fiction7.jpg',
        price: "Exchange",
        condition: 'Like New',
        publishedDate: DateTime(2018),
        isAvailable: true,
      ),
      Book(
        id: '19',
        title: 'Thinking, Fast and Slow',
        author: 'Daniel Kahneman',
        category: 'Non-Fiction',
        description: 'Explores the two systems of thought: fast intuition and slow reasoning.',
        ownerId: 'owner19',
        ownerName: 'Sherif Omar',
        ownerContact: '01088990011',
        imageUrl: 'assets/images/Non-Fiction8.jpg',
        price: "160 EGP",
        condition: 'Good',
        publishedDate: DateTime(2011),
        isAvailable: true,
      ),
      Book(
        id: '20',
        title: 'The Subtle Art of Not Giving a F*ck',
        author: 'Mark Manson',
        category: 'Non-Fiction',
        description: 'A counterintuitive approach to living a good life by prioritizing what matters.',
        ownerId: 'owner20',
        ownerName: 'Ramy Essam',
        ownerContact: '01099001122',
        imageUrl: 'assets/images/Non-Fiction9.jpg',
        price: "Exchange",
        condition: 'Used',
        publishedDate: DateTime(2016),
        isAvailable: true,
      ),
      Book(
        id: '21',
        title: 'Outliers: The Story of Success',
        author: 'Malcolm Gladwell',
        category: 'Non-Fiction',
        description: 'Examines the factors that contribute to high levels of success.',
        ownerId: 'owner21',
        ownerName: 'Hassan Mahmoud',
        ownerContact: '01000112233',
        imageUrl: 'assets/images/Non-Fiction10.jpg',
        price: "135 EGP",
        condition: 'Good',
        publishedDate: DateTime(2008),
        isAvailable: true,
      ),

      // Romance
      Book(
        id: '22',
        title: 'The Notebook',
        author: 'Nicholas Sparks',
        category: 'Romance',
        description: 'A heartwarming love story about Noah and Allie, who overcome obstacles to be together.',
        ownerId: 'owner22',
        ownerName: 'Layla Mohamed',
        ownerContact: '01011223344',
        imageUrl: 'assets/images/Romance1.jpg',
        price: "Exchange",
        condition: 'Like New',
        publishedDate: DateTime(1996),
        isAvailable: true,
      ),
      Book(
        id: '23',
        title: 'Pride and Prejudice',
        author: 'Jane Austen',
        category: 'Romance',
        description: 'A classic tale of love and misunderstandings between Elizabeth Bennet and Mr. Darcy.',
        ownerId: 'owner23',
        ownerName: 'Omar Khaled',
        ownerContact: '01022334455',
        imageUrl: 'assets/images/Romance2.jpg',
        price: "85 EGP",
        condition: 'Good',
        publishedDate: DateTime(1813),
        isAvailable: true,
      ),
      Book(
        id: '24',
        title: 'Me Before You',
        author: 'Jojo Moyes',
        category: 'Romance',
        description: 'A touching story about Louisa Clark and Will Traynor, who find love in unexpected circumstances.',
        ownerId: 'owner24',
        ownerName: 'Nada Samir',
        ownerContact: '01033445566',
        imageUrl: 'assets/images/Romance3.jpg',
        price: "Exchange",
        condition: 'Used',
        publishedDate: DateTime(2012),
        isAvailable: true,
      ),
      Book(
        id: '25',
        title: 'The Fault in Our Stars',
        author: 'John Green',
        category: 'Romance',
        description: 'A bittersweet love story between two teenagers, Hazel and Gus, who meet in a cancer support group.',
        ownerId: 'owner25',
        ownerName: 'Yara Mahmoud',
        ownerContact: '01044556677',
        imageUrl: 'assets/images/Romance4.jpg',
        price: "110 EGP",
        condition: 'Like New',
        publishedDate: DateTime(2012),
        isAvailable: true,
      ),
      Book(
        id: '26',
        title: 'Outlander',
        author: 'Diana Gabaldon',
        category: 'Romance',
        description: 'A time-travel romance about Claire Randall, who falls in love with Jamie Fraser in 18th-century Scotland.',
        ownerId: 'owner26',
        ownerName: 'Karim Waleed',
        ownerContact: '01055667788',
        imageUrl: 'assets/images/Romance5.jpg',
        price: "Exchange",
        condition: 'Good',
        publishedDate: DateTime(1991),
        isAvailable: true,
      ),
      Book(
        id: '27',
        title: 'Red, White & Royal Blue',
        author: 'Casey McQuiston',
        category: 'Romance',
        description: 'A romantic comedy about the First Son of the U.S. falling in love with a British prince.',
        ownerId: 'owner27',
        ownerName: 'Dalia Nasser',
        ownerContact: '01066778899',
        imageUrl: 'assets/images/Romance6.jpg',
        price: "130 EGP",
        condition: 'Like New',
        publishedDate: DateTime(2019),
        isAvailable: true,
      ),
      Book(
        id: '28',
        title: 'Bridgerton: The Duke and I',
        author: 'Julia Quinn',
        category: 'Romance',
        description: 'A Regency-era romance about Daphne Bridgerton and the Duke of Hastings.',
        ownerId: 'owner28',
        ownerName: 'Mariam Adel',
        ownerContact: '01077889900',
        imageUrl: 'assets/images/Romance7.jpg',
        price: "Exchange",
        condition: 'Used',
        publishedDate: DateTime(2000),
        isAvailable: true,
      ),
      Book(
        id: '29',
        title: 'It Ends with Us',
        author: 'Colleen Hoover',
        category: 'Romance',
        description: 'A powerful love story about Lily Bloom and her complicated relationship with Ryle Kincaid.',
        ownerId: 'owner29',
        ownerName: 'Hana Tarek',
        ownerContact: '01088990011',
        imageUrl: 'assets/images/Romance8.jpg',
        price: "150 EGP",
        condition: 'Good',
        publishedDate: DateTime(2016),
        isAvailable: true,
      ),
      Book(
        id: '30',
        title: 'The Hating Game',
        author: 'Sally Thorne',
        category: 'Romance',
        description: 'A workplace enemies-to-lovers romance between Lucy Hutton and Joshua Templeman.',
        ownerId: 'owner30',
        ownerName: 'Ziad Farouk',
        ownerContact: '01099001122',
        imageUrl: 'assets/images/Romance9.jpg',
        price: "Exchange",
        condition: 'Like New',
        publishedDate: DateTime(2016),
        isAvailable: true,
      ),
      Book(
        id: '31',
        title: 'Beach Read',
        author: 'Emily Henry',
        category: 'Romance',
        description: 'Two rival authors swap genres and unexpectedly fall in love during a summer getaway.',
        ownerId: 'owner31',
        ownerName: 'Lina Sherif',
        ownerContact: '01000112233',
        imageUrl: 'assets/images/Romance10.jpg',
        price: "125 EGP",
        condition: 'Good',
        publishedDate: DateTime(2020),
        isAvailable: true,
      ),

      // Mystery
      Book(
        id: '32',
        title: 'The Girl with the Dragon Tattoo',
        author: 'Stieg Larsson',
        category: 'Mystery',
        description: 'A journalist and a hacker investigate a 40-year-old disappearance in a wealthy family.',
        ownerId: 'owner32',
        ownerName: 'Nora Ahmed',
        ownerContact: '01011223344',
        imageUrl: 'assets/images/Mystery1.jpg',
        price: "Exchange",
        condition: 'Good',
        publishedDate: DateTime(2005),
        isAvailable: true,
      ),
      Book(
        id: '33',
        title: 'Gone Girl',
        author: 'Gillian Flynn',
        category: 'Mystery',
        description: 'A woman mysteriously disappears on her wedding anniversary, and her husband becomes the prime suspect.',
        ownerId: 'owner33',
        ownerName: 'Karim Hassan',
        ownerContact: '01022334455',
        imageUrl: 'assets/images/Mystery2.jpg',
        price: "130 EGP",
        condition: 'Like New',
        publishedDate: DateTime(2012),
        isAvailable: true,
      ),
      Book(
        id: '34',
        title: 'The Da Vinci Code',
        author: 'Dan Brown',
        category: 'Mystery',
        description: 'A symbologist and cryptologist try to solve a murder mystery connected to a religious conspiracy.',
        ownerId: 'owner34',
        ownerName: 'Lina Mahmoud',
        ownerContact: '01033445566',
        imageUrl: 'assets/images/Mystery3.jpg',
        price: "Exchange",
        condition: 'Used',
        publishedDate: DateTime(2003),
        isAvailable: true,
      ),
      Book(
        id: '35',
        title: 'The Silent Patient',
        author: 'Alex Michaelides',
        category: 'Mystery',
        description: 'A criminal psychotherapist tries to uncover why a famous painter shot her husband and then stopped speaking.',
        ownerId: 'owner35',
        ownerName: 'Omar Samir',
        ownerContact: '01044556677',
        imageUrl: 'assets/images/Mystery4.jpg',
        price: "150 EGP",
        condition: 'Like New',
        publishedDate: DateTime(2019),
        isAvailable: true,
      ),
      Book(
        id: '36',
        title: 'And Then There Were None',
        author: 'Agatha Christie',
        category: 'Mystery',
        description: 'Ten strangers are invited to an isolated island, where they begin to die one by one.',
        ownerId: 'owner36',
        ownerName: 'Yara Adel',
        ownerContact: '01055667788',
        imageUrl: 'assets/images/Mystery5.jpg',
        price: "Exchange",
        condition: 'Good',
        publishedDate: DateTime(1939),
        isAvailable: true,
      ),
      Book(
        id: '37',
        title: 'The Woman in the Window',
        author: 'A.J. Finn',
        category: 'Mystery',
        description: 'An agoraphobic woman thinks she witnesses a crime in her neighbor\'s house.',
        ownerId: 'owner37',
        ownerName: 'Sherif Nasser',
        ownerContact: '01066778899',
        imageUrl: 'assets/images/Mystery6.jpg',
        price: "110 EGP",
        condition: 'Used',
        publishedDate: DateTime(2018),
        isAvailable: true,
      ),
      Book(
        id: '38',
        title: 'Sharp Objects',
        author: 'Gillian Flynn',
        category: 'Mystery',
        description: 'A journalist returns to her hometown to cover the murders of two young girls.',
        ownerId: 'owner38',
        ownerName: 'Dina Waleed',
        ownerContact: '01077889900',
        imageUrl: 'assets/images/Mystery7.jpg',
        price: "Exchange",
        condition: 'Good',
        publishedDate: DateTime(2006),
        isAvailable: true,
      ),
      Book(
        id: '39',
        title: 'The Murder of Roger Ackroyd',
        author: 'Agatha Christie',
        category: 'Mystery',
        description: 'Hercule Poirot investigates the murder of a wealthy man in a small village.',
        ownerId: 'owner39',
        ownerName: 'Hassan Tarek',
        ownerContact: '01088990011',
        imageUrl: 'assets/images/Mystery8.jpg',
        price: "85 EGP",
        condition: 'Used',
        publishedDate: DateTime(1926),
        isAvailable: true,
      ),
      Book(
        id: '40',
        title: 'In the Woods',
        author: 'Tana French',
        category: 'Mystery',
        description: 'A detective investigates a murder that may be connected to his own childhood trauma.',
        ownerId: 'owner40',
        ownerName: 'Mona Essam',
        ownerContact: '01099001122',
        imageUrl: 'assets/images/Mystery9.jpg',
        price: "Exchange",
        condition: 'Like New',
        publishedDate: DateTime(2007),
        isAvailable: true,
      ),
      Book(
        id: '41',
        title: 'The Girl on the Train',
        author: 'Paula Hawkins',
        category: 'Mystery',
        description: 'A woman becomes entangled in a missing persons investigation that she witnessed from her train.',
        ownerId: 'owner41',
        ownerName: 'Ramy Farouk',
        ownerContact: '01000112233',
        imageUrl: 'assets/images/Mystery10.jpg',
        price: "115 EGP",
        condition: 'Good',
        publishedDate: DateTime(2015),
        isAvailable: true,
      ),

      // // Fantasy
      Book(
        id: '42',
        title: 'The Hobbit',
        author: 'J.R.R. Tolkien',
        category: 'Fantasy',
        description: 'A hobbit goes on an adventure to reclaim treasure guarded by a dragon.',
        ownerId: 'owner101',
        ownerName: 'John Smith',
        ownerContact: '01112223334',
        imageUrl: 'assets/images/Fantasy1.jpg',
        price: "Exchange",
        condition: 'Excellent',
        publishedDate: DateTime(1937),
        isAvailable: true,
      ),
      Book(
        id: '43',
        title: 'Harry Potter and the Sorcerer\'s Stone',
        author: 'J.K. Rowling',
        category: 'Fantasy',
        description: 'A young boy discovers he is a wizard and attends a magical school.',
        ownerId: 'owner102',
        ownerName: 'Sarah Johnson',
        ownerContact: '01223334455',
        imageUrl: 'assets/images/Fantasy2.jpg',
        price: "130 EGP",
        condition: 'Good',
        publishedDate: DateTime(1997),
        isAvailable: true,
      ),
      Book(
        id: '44',
        title: 'A Game of Thrones',
        author: 'George R.R. Martin',
        category: 'Fantasy',
        description: 'Noble families fight for control of the mythical land of Westeros.',
        ownerId: 'owner103',
        ownerName: 'Michael Brown',
        ownerContact: '01011223344',
        imageUrl: 'assets/images/Fantasy3.jpg',
        price: "Exchange",
        condition: 'Very Good',
        publishedDate: DateTime(1996),
        isAvailable: true,
      ),
      // Book(
      //   id: '45',
      //   title: 'The Name of the Wind',
      //   author: 'Patrick Rothfuss',
      //   category: 'Fantasy',
      //   description: 'The story of Kvothe, an adventurer and musician with a mysterious past.',
      //   ownerId: 'owner104',
      //   ownerName: 'Emily Davis',
      //   ownerContact: '01122334455',
      //   imageUrl: 'assets/images/name_of_wind.jpg',
      //   price: 140,
      //   condition: 'Good',
      //   publishedDate: DateTime(2007),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '46',
      //   title: 'Mistborn: The Final Empire',
      //   author: 'Brandon Sanderson',
      //   category: 'Fantasy',
      //   description: 'A young woman joins a group of rebels to overthrow a tyrannical ruler.',
      //   ownerId: 'owner105',
      //   ownerName: 'David Wilson',
      //   ownerContact: '01233445566',
      //   imageUrl: 'assets/images/mistborn.jpg',
      //   price: 125,
      //   condition: 'Excellent',
      //   publishedDate: DateTime(2006),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '47',
      //   title: 'The Way of Kings',
      //   author: 'Brandon Sanderson',
      //   category: 'Fantasy',
      //   description: 'An epic tale of war, honor, and magic in the world of Roshar.',
      //   ownerId: 'owner106',
      //   ownerName: 'Lisa Taylor',
      //   ownerContact: '01022334455',
      //   imageUrl: 'assets/images/way_of_kings.jpg',
      //   price: 160,
      //   condition: 'Very Good',
      //   publishedDate: DateTime(2010),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '48',
      //   title: 'The Lies of Locke Lamora',
      //   author: 'Scott Lynch',
      //   category: 'Fantasy',
      //   description: 'A group of thieves pull off elaborate heists in a fantasy Venice-like city.',
      //   ownerId: 'owner107',
      //   ownerName: 'Robert Clark',
      //   ownerContact: '01133445566',
      //   imageUrl: 'assets/images/locke_lamora.jpg',
      //   price: 135,
      //   condition: 'Good',
      //   publishedDate: DateTime(2006),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '49',
      //   title: 'The Fifth Season',
      //   author: 'N.K. Jemisin',
      //   category: 'Fantasy',
      //   description: 'A world-ending catastrophe forces people with magical abilities to survive.',
      //   ownerId: 'owner108',
      //   ownerName: 'Jessica Adams',
      //   ownerContact: '01244556677',
      //   imageUrl: 'assets/images/fifth_season.jpg',
      //   price: 145,
      //   condition: 'Excellent',
      //   publishedDate: DateTime(2015),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '50',
      //   title: 'The Priory of the Orange Tree',
      //   author: 'Samantha Shannon',
      //   category: 'Fantasy',
      //   description: 'A standalone epic fantasy about dragons, queens, and ancient prophecies.',
      //   ownerId: 'owner109',
      //   ownerName: 'Daniel White',
      //   ownerContact: '01033445566',
      //   imageUrl: 'assets/images/priory_orange_tree.jpg',
      //   price: 155,
      //   condition: 'Very Good',
      //   publishedDate: DateTime(2019),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '51',
      //   title: 'The Blade Itself',
      //   author: 'Joe Abercrombie',
      //   category: 'Fantasy',
      //   description: 'A dark and gritty fantasy following morally grey characters in a brutal world.',
      //   ownerId: 'owner110',
      //   ownerName: 'Sophia Martin',
      //   ownerContact: '01144556677',
      //   imageUrl: 'assets/images/blade_itself.jpg',
      //   price: 125,
      //   condition: 'Good',
      //   publishedDate: DateTime(2006),
      //   isAvailable: true,
      // ),

      // Science Fiction
      Book(
        id: '52',
        title: 'Dune',
        author: 'Frank Herbert',
        category: 'Science Fiction',
        description: 'A young man leads a rebellion on a desert planet rich with a powerful spice.',
        ownerId: 'owner201',
        ownerName: 'Paul Atreides',
        ownerContact: '01011223344',
        imageUrl: 'assets/images/Science Fiction1.jpg',
        price: "Exchange",
        condition: 'Excellent',
        publishedDate: DateTime(1965),
        isAvailable: true,
      ),
      Book(
        id: '53',
        title: 'Neuromancer',
        author: 'William Gibson',
        category: 'Science Fiction',
        description: 'A hacker is hired for one last job in a world of cybernetics and AI.',
        ownerId: 'owner202',
        ownerName: 'Case',
        ownerContact: '01122334455',
        imageUrl: 'assets/images/Science Fiction2.jpg',
        price: "120 EGP",
        condition: 'Good',
        publishedDate: DateTime(1984),
        isAvailable: true,
      ),
      // Book(
      //   id: '54',
      //   title: 'The Martian',
      //   author: 'Andy Weir',
      //   category: 'Science Fiction',
      //   description: 'An astronaut stranded on Mars uses science to survive.',
      //   ownerId: 'owner203',
      //   ownerName: 'Mark Watney',
      //   ownerContact: '01233445566',
      //   imageUrl: 'assets/images/martian.jpg',
      //   price: 130,
      //   condition: 'Very Good',
      //   publishedDate: DateTime(2011),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '55',
      //   title: 'Foundation',
      //   author: 'Isaac Asimov',
      //   category: 'Science Fiction',
      //   description: 'A mathematician predicts the fall of a galactic empire and plans its rebirth.',
      //   ownerId: 'owner204',
      //   ownerName: 'Hari Seldon',
      //   ownerContact: '01044556677',
      //   imageUrl: 'assets/images/foundation.jpg',
      //   price: 110,
      //   condition: 'Good',
      //   publishedDate: DateTime(1951),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '56',
      //   title: 'Snow Crash',
      //   author: 'Neal Stephenson',
      //   category: 'Science Fiction',
      //   description: 'A hacker and a courier uncover a conspiracy in a virtual reality world.',
      //   ownerId: 'owner205',
      //   ownerName: 'Hiro Protagonist',
      //   ownerContact: '01155667788',
      //   imageUrl: 'assets/images/snow_crash.jpg',
      //   price: 125,
      //   condition: 'Excellent',
      //   publishedDate: DateTime(1992),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '57',
      //   title: 'Ender\'s Game',
      //   author: 'Orson Scott Card',
      //   category: 'Science Fiction',
      //   description: 'A gifted child is trained to lead humanity in a war against aliens.',
      //   ownerId: 'owner206',
      //   ownerName: 'Ender Wiggin',
      //   ownerContact: '01266778899',
      //   imageUrl: 'assets/images/enders_game.jpg',
      //   price: 115,
      //   condition: 'Very Good',
      //   publishedDate: DateTime(1985),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '58',
      //   title: 'Hyperion',
      //   author: 'Dan Simmons',
      //   category: 'Science Fiction',
      //   description: 'Seven pilgrims journey to a mysterious planet to meet a deadly creature.',
      //   ownerId: 'owner207',
      //   ownerName: 'The Shrike',
      //   ownerContact: '01077889900',
      //   imageUrl: 'assets/images/hyperion.jpg',
      //   price: 135,
      //   condition: 'Good',
      //   publishedDate: DateTime(1989),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '59',
      //   title: 'The Left Hand of Darkness',
      //   author: 'Ursula K. Le Guin',
      //   category: 'Science Fiction',
      //   description: 'A human envoy navigates a planet where gender is fluid.',
      //   ownerId: 'owner208',
      //   ownerName: 'Genly Ai',
      //   ownerContact: '01188990011',
      //   imageUrl: 'assets/images/left_hand_darkness.jpg',
      //   price: 140,
      //   condition: 'Excellent',
      //   publishedDate: DateTime(1969),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '60',
      //   title: 'Altered Carbon',
      //   author: 'Richard K. Morgan',
      //   category: 'Science Fiction',
      //   description: 'A mercenary investigates a murder in a world where consciousness can be transferred.',
      //   ownerId: 'owner209',
      //   ownerName: 'Takeshi Kovacs',
      //   ownerContact: '01299001122',
      //   imageUrl: 'assets/images/altered_carbon.jpg',
      //   price: 150,
      //   condition: 'Very Good',
      //   publishedDate: DateTime(2002),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '61',
      //   title: 'Project Hail Mary',
      //   author: 'Andy Weir',
      //   category: 'Science Fiction',
      //   description: 'A lone astronaut must save Earth from an interstellar disaster.',
      //   ownerId: 'owner210',
      //   ownerName: 'Ryland Grace',
      //   ownerContact: '01000112233',
      //   imageUrl: 'assets/images/project_hail_mary.jpg',
      //   price: 155,
      //   condition: 'Good',
      //   publishedDate: DateTime(2021),
      //   isAvailable: true,
      // ),
      //
      // // Historical
      Book(
        id: '62',
        title: 'The Pillars of the Earth',
        author: 'Ken Follett',
        category: 'Historical',
        description: 'A sweeping epic of cathedral-building in 12th-century England.',
        ownerId: 'owner301',
        ownerName: 'Thomas Builder',
        ownerContact: '01112223344',
        imageUrl: 'assets/images/Historical1.jpg',
        price: "Exchange",
        condition: 'Excellent',
        publishedDate: DateTime(1989),
        isAvailable: true,
      ),
      Book(
        id: '63',
        title: 'All the Light We Cannot See',
        author: 'Anthony Doerr',
        category: 'Historical',
        description: 'A blind French girl and a German boy\'s paths collide in WWII.',
        ownerId: 'owner302',
        ownerName: 'Marie-Laure LeBlanc',
        ownerContact: '01223334455',
        imageUrl: 'assets/images/Historical2.jpg',
        price: "135 EGP",
        condition: 'Very Good',
        publishedDate: DateTime(2014),
        isAvailable: true,
      ),
      // Book(
      //   id: '64',
      //   title: 'The Book Thief',
      //   author: 'Markus Zusak',
      //   category: 'Historical',
      //   description: 'A young girl steals books in Nazi Germany, narrated by Death.',
      //   ownerId: 'owner303',
      //   ownerName: 'Liesel Meminger',
      //   ownerContact: '01033445566',
      //   imageUrl: 'assets/images/book_thief.jpg',
      //   price: 115,
      //   condition: 'Good',
      //   publishedDate: DateTime(2005),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '65',
      //   title: 'Wolf Hall',
      //   author: 'Hilary Mantel',
      //   category: 'Historical',
      //   description: 'Thomas Cromwell rises to power in the court of Henry VIII.',
      //   ownerId: 'owner304',
      //   ownerName: 'Thomas Cromwell',
      //   ownerContact: '01144556677',
      //   imageUrl: 'assets/images/wolf_hall.jpg',
      //   price: 140,
      //   condition: 'Excellent',
      //   publishedDate: DateTime(2009),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '66',
      //   title: 'Gone with the Wind',
      //   author: 'Margaret Mitchell',
      //   category: 'Historical',
      //   description: 'A Southern belle\'s survival during the American Civil War.',
      //   ownerId: 'owner305',
      //   ownerName: 'Scarlett O\'Hara',
      //   ownerContact: '01255667788',
      //   imageUrl: 'assets/images/gone_with_wind.jpg',
      //   price: 110,
      //   condition: 'Good',
      //   publishedDate: DateTime(1936),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '67',
      //   title: 'The Nightingale',
      //   author: 'Kristin Hannah',
      //   category: 'Historical',
      //   description: 'Two sisters resist Nazi occupation in WWII France.',
      //   ownerId: 'owner306',
      //   ownerName: 'Vianne Mauriac',
      //   ownerContact: '01066778899',
      //   imageUrl: 'assets/images/nightingale.jpg',
      //   price: 130,
      //   condition: 'Very Good',
      //   publishedDate: DateTime(2015),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '68',
      //   title: 'Shōgun',
      //   author: 'James Clavell',
      //   category: 'Historical',
      //   description: 'An English navigator becomes a samurai in feudal Japan.',
      //   ownerId: 'owner307',
      //   ownerName: 'John Blackthorne',
      //   ownerContact: '01177889900',
      //   imageUrl: 'assets/images/shogun.jpg',
      //   price: 150,
      //   condition: 'Excellent',
      //   publishedDate: DateTime(1975),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '69',
      //   title: 'The Paris Wife',
      //   author: 'Paula McLain',
      //   category: 'Historical',
      //   description: 'Ernest Hemingway\'s first marriage in 1920s Paris.',
      //   ownerId: 'owner308',
      //   ownerName: 'Hadley Richardson',
      //   ownerContact: '01288990011',
      //   imageUrl: 'assets/images/paris_wife.jpg',
      //   price: 120,
      //   condition: 'Good',
      //   publishedDate: DateTime(2011),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '70',
      //   title: 'The Alice Network',
      //   author: 'Kate Quinn',
      //   category: 'Historical',
      //   description: 'A female spy network in WWI and a post-WWII search for truth.',
      //   ownerId: 'owner309',
      //   ownerName: 'Eve Gardiner',
      //   ownerContact: '01099001122',
      //   imageUrl: 'assets/images/alice_network.jpg',
      //   price: 125,
      //   condition: 'Very Good',
      //   publishedDate: DateTime(2017),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '71',
      //   title: 'The Tattooist of Auschwitz',
      //   author: 'Heather Morris',
      //   category: 'Historical',
      //   description: 'A Holocaust survivor\'s love story in a concentration camp.',
      //   ownerId: 'owner310',
      //   ownerName: 'Lale Sokolov',
      //   ownerContact: '01100112233',
      //   imageUrl: 'assets/images/tattooist_auschwitz.jpg',
      //   price: 118,
      //   condition: 'Good',
      //   publishedDate: DateTime(2018),
      //   isAvailable: true,
      // ),
      //
      // // Business
      //
      Book(
        id: '72',
        title: 'Rich Dad Poor Dad',
        author: 'Robert Kiyosaki',
        category: 'Business',
        description: 'Financial lessons from two father figures with contrasting money mindsets.',
        ownerId: 'owner401',
        ownerName: 'Alex Johnson',
        ownerContact: '01011223344',
        imageUrl: 'assets/images/Business1.jpg',
        price: "95 EGP",
        condition: 'Good',
        publishedDate: DateTime(1997),
        isAvailable: true,
      ),
      // Book(
      //   id: '73',
      //   title: 'The Lean Startup',
      //   author: 'Eric Ries',
      //   category: 'Business',
      //   description: 'How to build a successful startup through continuous innovation.',
      //   ownerId: 'owner402',
      //   ownerName: 'Sarah Chen',
      //   ownerContact: '01122334455',
      //   imageUrl: 'assets/images/lean_startup.jpg',
      //   price: 120,
      //   condition: 'Excellent',
      //   publishedDate: DateTime(2011),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '74',
      //   title: 'Good to Great',
      //   author: 'Jim Collins',
      //   category: 'Business',
      //   description: 'Why some companies make the leap and others don\'t.',
      //   ownerId: 'owner403',
      //   ownerName: 'Michael Brown',
      //   ownerContact: '01233445566',
      //   imageUrl: 'assets/images/good_to_great.jpg',
      //   price: 110,
      //   condition: 'Very Good',
      //   publishedDate: DateTime(2001),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '75',
      //   title: 'Atomic Habits',
      //   author: 'James Clear',
      //   category: 'Business',
      //   description: 'Tiny changes that lead to remarkable results in business and life.',
      //   ownerId: 'owner404',
      //   ownerName: 'Emily Davis',
      //   ownerContact: '01044556677',
      //   imageUrl: 'assets/images/atomic_habits.jpg',
      //   price: 105,
      //   condition: 'Excellent',
      //   publishedDate: DateTime(2018),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '76',
      //   title: 'The 4-Hour Workweek',
      //   author: 'Timothy Ferriss',
      //   category: 'Business',
      //   description: 'Escape the 9-5, live anywhere, and join the new rich.',
      //   ownerId: 'owner405',
      //   ownerName: 'David Wilson',
      //   ownerContact: '01155667788',
      //   imageUrl: 'assets/images/4hour_workweek.jpg',
      //   price: 115,
      //   condition: 'Good',
      //   publishedDate: DateTime(2007),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '77',
      //   title: 'Think and Grow Rich',
      //   author: 'Napoleon Hill',
      //   category: 'Business',
      //   description: 'Classic principles of success and wealth creation.',
      //   ownerId: 'owner406',
      //   ownerName: 'Lisa Taylor',
      //   ownerContact: '01266778899',
      //   imageUrl: 'assets/images/think_grow_rich.jpg',
      //   price: 85,
      //   condition: 'Fair',
      //   publishedDate: DateTime(1937),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '78',
      //   title: 'Zero to One',
      //   author: 'Peter Thiel',
      //   category: 'Business',
      //   description: 'Notes on startups, or how to build the future.',
      //   ownerId: 'owner407',
      //   ownerName: 'Robert Clark',
      //   ownerContact: '01077889900',
      //   imageUrl: 'assets/images/zero_to_one.jpg',
      //   price: 125,
      //   condition: 'Very Good',
      //   publishedDate: DateTime(2014),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '79',
      //   title: 'The Hard Thing About Hard Things',
      //   author: 'Ben Horowitz',
      //   category: 'Business',
      //   description: 'Building a business when there are no easy answers.',
      //   ownerId: 'owner408',
      //   ownerName: 'Jessica Adams',
      //   ownerContact: '01188990011',
      //   imageUrl: 'assets/images/hard_things.jpg',
      //   price: 130,
      //   condition: 'Excellent',
      //   publishedDate: DateTime(2014),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '80',
      //   title: 'Influence: The Psychology of Persuasion',
      //   author: 'Robert Cialdini',
      //   category: 'Business',
      //   description: 'The science behind how people say "yes" and how to apply it.',
      //   ownerId: 'owner409',
      //   ownerName: 'Daniel White',
      //   ownerContact: '01299001122',
      //   imageUrl: 'assets/images/influence.jpg',
      //   price: 100,
      //   condition: 'Good',
      //   publishedDate: DateTime(1984),
      //   isAvailable: true,
      // ),
      // Book(
      //   id: '81',
      //   title: 'The 100 dollar Startup',
      //   author: 'Chris Guillebeau',
      //   category: 'Business',
      //   description: 'Reinvent the way you make a living with minimal resources.',
      //   ownerId: 'owner410',
      //   ownerName: 'Sophia Martin',
      //   ownerContact: '01000112233',
      //   imageUrl: 'assets/images/100_startup.jpg',
      //   price: 90,
      //   condition: 'Very Good',
      //   publishedDate: DateTime(2012),
      //   isAvailable: true,
      // ),


    ];

    return allBooks.where((book) => book.category == category).toList();
  }

  Future<List<BookCategory>> getAllCategories() async {
    return [
      BookCategory(name: 'Fiction', icon: Icons.book),
      BookCategory(name: 'Non-Fiction', icon: Icons.article),
      BookCategory(name: 'Romance', icon: Icons.favorite),
      BookCategory(name: 'Mystery', icon: Icons.search),
      BookCategory(name: 'Fantasy', icon: Icons.auto_awesome),
      BookCategory(name: 'Science Fiction', icon: Icons.rocket_launch),
      BookCategory(name: 'Historical', icon: Icons.history),
      BookCategory(name: 'Business', icon: Icons.business),
      // BookCategory(name: 'Children\'s Books', icon: Icons.child_care),
      // BookCategory(name: 'Religion', icon: Icons.people),
      // BookCategory(name: 'Educational', icon: Icons.school),
      // BookCategory(name: 'Biography', icon: Icons.person),
    ];
  }
}