// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWEOSqDDRaGP1Q5dISxVUNR0By20C5XB8',
    appId: '1:582343544338:web:1d7dfa7b4b28e2514c52cb',
    messagingSenderId: '582343544338',
    projectId: 'booknest-137bb',
    authDomain: 'booknest-137bb.firebaseapp.com',
    storageBucket: 'booknest-137bb.firebasestorage.app',
    measurementId: 'G-PMXQ1CXBCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4kUh02GFo5b9oczPKQPu3JeV4ih1kjXQ',
    appId: '1:582343544338:android:2c39e93c4337d5004c52cb',
    messagingSenderId: '582343544338',
    projectId: 'booknest-137bb',
    storageBucket: 'booknest-137bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM7RF3qQ7UxNGmMY79mEXy8mcSAiqcLqQ',
    appId: '1:582343544338:ios:8e6e58dd6801fe1e4c52cb',
    messagingSenderId: '582343544338',
    projectId: 'booknest-137bb',
    storageBucket: 'booknest-137bb.firebasestorage.app',
    iosBundleId: 'com.example.booknest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM7RF3qQ7UxNGmMY79mEXy8mcSAiqcLqQ',
    appId: '1:582343544338:ios:8e6e58dd6801fe1e4c52cb',
    messagingSenderId: '582343544338',
    projectId: 'booknest-137bb',
    storageBucket: 'booknest-137bb.firebasestorage.app',
    iosBundleId: 'com.example.booknest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWEOSqDDRaGP1Q5dISxVUNR0By20C5XB8',
    appId: '1:582343544338:web:469b041793dff4734c52cb',
    messagingSenderId: '582343544338',
    projectId: 'booknest-137bb',
    authDomain: 'booknest-137bb.firebaseapp.com',
    storageBucket: 'booknest-137bb.firebasestorage.app',
    measurementId: 'G-78Z4QRRQ30',
  );
}
